import type { ReplayManifest } from "../capture/replay.js";
import type {
  ReviewedTrajectoryAction,
  TrajectoryAction,
  TrajectorySpan,
} from "../capture/trajectory.js";
import type { ExportedReplayManifest, ReviewedExportManifest } from "./export-manifest.js";

/**
 * Local-movement learning: model layer.
 *
 * The capture pipeline (recorder/trajectory/replay + device/os/browser adapters)
 * records movements; the exporter turns approved trajectories into a reviewed
 * dataset. This module closes the loop's last two pieces — objective #2 (c)
 * "post-train a local model to repeat the recorded movements" and (d)
 * "generalize to perform new but related movements" — with an in-process,
 * deterministic, pluggable model backend.
 *
 * The real on-device path (MLX/Axolotl) is generated by
 * {@link LocalAppleSiliconTrainingRunner}. That path cannot run in the cloud, so
 * the backend below is designed so tests (and the engine's own validation) can
 * exercise train -> predict -> generate -> eval entirely in memory on synthetic
 * event streams. A different backend (a real small local model) can implement
 * {@link MovementModelBackend} without any other code changing.
 */

/** A canonical, replayable movement token, e.g. `device:tap:submit-button`. */
export type MovementToken = string;

/** One recorded (or synthetic) movement sequence — the actions of a trajectory. */
export type MovementSequence = {
  id: string;
  tokens: MovementToken[];
};

/** The dataset a backend trains on. */
export type MovementTrainingDataset = {
  version: 1;
  sequences: MovementSequence[];
};

export type MovementCandidate = {
  token: MovementToken;
  probability: number;
};

export type MovementPrediction = {
  /** Highest-probability next token, or `undefined` when the model is empty. */
  token: MovementToken | undefined;
  probability: number;
  /** All next-token candidates for the matched context, most-likely first. */
  candidates: MovementCandidate[];
  /** Context order that produced the prediction after backoff (0 = unigram). */
  matchedOrder: number;
};

export type MovementModelInfo = {
  backend: string;
  order: number;
  vocabulary: MovementToken[];
  sequenceCount: number;
  tokenCount: number;
};

export type MovementTrainingOptions = {
  /** Max context length (Markov order). Defaults to 2. */
  order?: number;
};

/** A trained model: deterministic inference over recorded movements. */
export interface MovementModel {
  readonly info: MovementModelInfo;
  /** Predict the next movement given the trailing context. */
  predictNext(context: MovementToken[]): MovementPrediction;
  /** Roll out a continuation (argmax, deterministic) after `seed`. */
  generate(seed: MovementToken[], maxLength: number): MovementToken[];
  /** Portable snapshot so a trained model can be persisted/reloaded. */
  serialize(): SerializedMovementModel;
}

/** Pluggable training backend. Swap this for a real on-device model. */
export interface MovementModelBackend {
  readonly name: string;
  train(dataset: MovementTrainingDataset, options?: MovementTrainingOptions): Promise<MovementModel>;
}

// ---------------------------------------------------------------------------
// Tokenization — derive canonical movement tokens from recorded actions.
// ---------------------------------------------------------------------------

function slug(value: string): string {
  const cleaned = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return cleaned.length > 0 ? cleaned : "action";
}

/** Canonical token for a recorded action, using gesture/target metadata when present. */
export function movementTokenFromAction(
  action: Pick<TrajectoryAction, "tool" | "summary"> & { metadata?: Record<string, unknown> },
): MovementToken {
  const meta = action.metadata ?? {};
  const gesture = typeof meta.gesture === "string" ? meta.gesture : undefined;
  const target =
    typeof meta.target === "string"
      ? meta.target
      : typeof meta.direction === "string"
        ? meta.direction
        : undefined;
  const parts = [slug(action.tool)];
  if (gesture) {
    parts.push(slug(gesture));
  }
  if (target) {
    parts.push(slug(target));
  }
  if (!gesture && !target) {
    parts.push(slug(action.summary));
  }
  return parts.join(":");
}

/** Build a movement sequence from a trajectory (prefers reviewed/redacted actions). */
export function movementSequenceFromTrajectory(trajectory: TrajectorySpan): MovementSequence {
  const reviewed: ReviewedTrajectoryAction[] | undefined = trajectory.review?.redactedActions;
  const actions = reviewed ?? trajectory.actions;
  return {
    id: trajectory.id,
    tokens: actions.map((action) => movementTokenFromAction(action)),
  };
}

/** Build a movement sequence from a replay timeline (action events only). */
export function movementSequenceFromReplay(replay: ReplayManifest | ExportedReplayManifest): MovementSequence {
  const tokens = replay.events
    .filter((event): event is Extract<typeof event, { kind: "action" }> => event.kind === "action")
    .map((event) => movementTokenFromAction({ tool: event.tool, summary: event.summary }));
  const id = replay.trajectoryIds.length > 0 ? replay.trajectoryIds.join("+") : replay.sessionId;
  return { id, tokens };
}

/** Assemble a training dataset from a reviewed export manifest's replays. */
export function movementDatasetFromExport(manifest: ReviewedExportManifest): MovementTrainingDataset {
  const sequences = manifest.replays
    .map((replay) => movementSequenceFromReplay(replay))
    .filter((sequence) => sequence.tokens.length > 0);
  return { version: 1, sequences };
}

// ---------------------------------------------------------------------------
// Deterministic n-gram backend with stupid-backoff smoothing.
// ---------------------------------------------------------------------------

/** Serialized counts: `orders[o]` maps a context key to next-token counts. */
export type SerializedMovementModel = {
  backend: string;
  order: number;
  sequenceCount: number;
  tokenCount: number;
  vocabulary: MovementToken[];
  orders: Array<Record<string, Record<MovementToken, number>>>;
};

const CONTEXT_SEPARATOR = "";

/**
 * Internal end-of-sequence sentinel. Learned as a next-token so the model knows
 * when a recorded workflow completes, which lets {@link MovementModel.generate}
 * stop naturally instead of looping via unigram backoff. Kept out of the public
 * vocabulary and filtered from {@link MovementModel.predictNext} results.
 */
const MOVEMENT_EOS = "EOS";

function contextKey(context: MovementToken[]): string {
  return context.join(CONTEXT_SEPARATOR);
}

/**
 * Order-k Markov model. For each position it learns next-token counts at every
 * context length 0..k; inference tries the longest available context and backs
 * off to shorter ones (down to the unigram distribution), which is what lets it
 * predict sensible next movements for *unseen but related* contexts.
 */
class MarkovMovementModel implements MovementModel {
  readonly info: MovementModelInfo;
  private readonly orders: Array<Map<string, Map<MovementToken, number>>>;
  private readonly totals: Array<Map<string, number>>;
  private readonly order: number;

  constructor(snapshot: SerializedMovementModel) {
    this.order = snapshot.order;
    this.orders = snapshot.orders.map((table) => {
      const map = new Map<string, Map<MovementToken, number>>();
      for (const [ctx, counts] of Object.entries(table)) {
        map.set(ctx, new Map(Object.entries(counts)));
      }
      return map;
    });
    this.totals = this.orders.map((table) => {
      const totals = new Map<string, number>();
      for (const [ctx, counts] of table.entries()) {
        let sum = 0;
        for (const value of counts.values()) {
          sum += value;
        }
        totals.set(ctx, sum);
      }
      return totals;
    });
    this.info = {
      backend: snapshot.backend,
      order: snapshot.order,
      vocabulary: [...snapshot.vocabulary],
      sequenceCount: snapshot.sequenceCount,
      tokenCount: snapshot.tokenCount,
    };
  }

  /** Raw backoff prediction including the EOS sentinel. Used by generation. */
  private predictRaw(context: MovementToken[]): { candidates: MovementCandidate[]; matchedOrder: number } {
    const maxOrder = Math.min(this.order, context.length);
    for (let order = maxOrder; order >= 0; order -= 1) {
      const table = this.orders[order];
      if (!table) {
        continue;
      }
      const key = contextKey(order === 0 ? [] : context.slice(context.length - order));
      const counts = table.get(key);
      const total = this.totals[order]?.get(key) ?? 0;
      if (counts && total > 0) {
        return { candidates: rankCandidates(counts, total), matchedOrder: order };
      }
    }
    return { candidates: [], matchedOrder: 0 };
  }

  predictNext(context: MovementToken[]): MovementPrediction {
    const raw = this.predictRaw(context);
    // The EOS sentinel is an internal control token; never surface it as a movement.
    const candidates = raw.candidates.filter((candidate) => candidate.token !== MOVEMENT_EOS);
    const top = candidates[0];
    return {
      token: top?.token,
      probability: top?.probability ?? 0,
      candidates,
      matchedOrder: candidates.length > 0 ? raw.matchedOrder : 0,
    };
  }

  generate(seed: MovementToken[], maxLength: number): MovementToken[] {
    const produced: MovementToken[] = [];
    const context = [...seed];
    for (let index = 0; index < maxLength; index += 1) {
      const { candidates } = this.predictRaw(context);
      const top = candidates[0];
      // Stop when the model has learned the sequence ends here, or dead-ends.
      if (!top || top.token === MOVEMENT_EOS) {
        break;
      }
      produced.push(top.token);
      context.push(top.token);
    }
    return produced;
  }

  serialize(): SerializedMovementModel {
    return {
      backend: this.info.backend,
      order: this.order,
      sequenceCount: this.info.sequenceCount,
      tokenCount: this.info.tokenCount,
      vocabulary: [...this.info.vocabulary],
      orders: this.orders.map((table) => {
        const record: Record<string, Record<MovementToken, number>> = {};
        for (const [ctx, counts] of table.entries()) {
          record[ctx] = Object.fromEntries(counts.entries());
        }
        return record;
      }),
    };
  }
}

function rankCandidates(counts: Map<MovementToken, number>, total: number): MovementCandidate[] {
  return [...counts.entries()]
    .map(([token, count]) => ({ token, probability: count / total }))
    .sort((a, b) => {
      if (b.probability !== a.probability) {
        return b.probability - a.probability;
      }
      return a.token < b.token ? -1 : a.token > b.token ? 1 : 0;
    });
}

/** The default in-process backend. Deterministic; safe to run in the cloud/CI. */
export class MarkovMovementBackend implements MovementModelBackend {
  readonly name = "markov-backoff";

  async train(dataset: MovementTrainingDataset, options?: MovementTrainingOptions): Promise<MovementModel> {
    const order = Math.max(0, Math.trunc(options?.order ?? 2));
    const orders: Array<Record<string, Record<MovementToken, number>>> = Array.from(
      { length: order + 1 },
      () => ({}),
    );
    const vocabulary = new Set<MovementToken>();
    let tokenCount = 0;

    for (const sequence of dataset.sequences) {
      // Append EOS so the model learns where a workflow ends (drives generate()).
      const tokens = sequence.tokens.length > 0 ? [...sequence.tokens, MOVEMENT_EOS] : [];
      for (let index = 0; index < tokens.length; index += 1) {
        const next = tokens[index];
        if (next === undefined) {
          continue;
        }
        if (next !== MOVEMENT_EOS) {
          vocabulary.add(next);
          tokenCount += 1;
        }
        const maxOrder = Math.min(order, index);
        for (let o = 0; o <= maxOrder; o += 1) {
          const context = o === 0 ? [] : tokens.slice(index - o, index);
          const key = contextKey(context);
          const table = orders[o] as Record<string, Record<MovementToken, number>>;
          const bucket = (table[key] ??= {});
          bucket[next] = (bucket[next] ?? 0) + 1;
        }
      }
    }

    const snapshot: SerializedMovementModel = {
      backend: this.name,
      order,
      sequenceCount: dataset.sequences.length,
      tokenCount,
      vocabulary: [...vocabulary].sort(),
      orders,
    };
    return new MarkovMovementModel(snapshot);
  }
}

/** Reload a persisted model snapshot for inference. */
export function loadMovementModel(snapshot: SerializedMovementModel): MovementModel {
  return new MarkovMovementModel(snapshot);
}

// ---------------------------------------------------------------------------
// Generalization eval — next-token replay fidelity on held-out sequences.
// ---------------------------------------------------------------------------

export type MovementSequenceEval = {
  id: string;
  predicted: number;
  correct: number;
  accuracy: number;
};

export type MovementEvalResult = {
  sequenceCount: number;
  predictedCount: number;
  correctCount: number;
  /** Fraction of next-token predictions that matched the recorded movement. */
  topOneAccuracy: number;
  perSequence: MovementSequenceEval[];
};

/**
 * Measure how faithfully the model reproduces held-out movements: for every
 * position it predicts the next token from the preceding context and compares
 * against what was actually recorded. Running this on trajectories the model was
 * NOT trained on measures generalization to new-but-related movements.
 */
export function evaluateMovementModel(
  model: MovementModel,
  heldOut: MovementTrainingDataset,
): MovementEvalResult {
  let predictedCount = 0;
  let correctCount = 0;
  const perSequence: MovementSequenceEval[] = [];

  for (const sequence of heldOut.sequences) {
    let predicted = 0;
    let correct = 0;
    for (let index = 0; index < sequence.tokens.length; index += 1) {
      const context = sequence.tokens.slice(0, index);
      const prediction = model.predictNext(context);
      predicted += 1;
      predictedCount += 1;
      if (prediction.token === sequence.tokens[index]) {
        correct += 1;
        correctCount += 1;
      }
    }
    perSequence.push({
      id: sequence.id,
      predicted,
      correct,
      accuracy: predicted > 0 ? correct / predicted : 0,
    });
  }

  return {
    sequenceCount: heldOut.sequences.length,
    predictedCount,
    correctCount,
    topOneAccuracy: predictedCount > 0 ? correctCount / predictedCount : 0,
    perSequence,
  };
}

// ---------------------------------------------------------------------------
// Synthetic event-stream generator — validate the pipeline without real OS input.
// ---------------------------------------------------------------------------

export type SyntheticMovementWorkflow = {
  name: string;
  /** Ordered steps; each step is a set of interchangeable token variants. */
  steps: MovementToken[][];
};

export type SyntheticMovementOptions = {
  seed: number;
  sequenceCount: number;
  workflows?: SyntheticMovementWorkflow[];
};

/** Deterministic PRNG (mulberry32) — reproducible synthetic streams, no global RNG. */
function makePrng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const DEFAULT_SYNTHETIC_WORKFLOWS: SyntheticMovementWorkflow[] = [
  {
    name: "compose-message",
    steps: [
      ["device:tap:app-icon"],
      ["device:tap:compose-button", "device:tap:new-button"],
      ["device:tap:recipient-field"],
      ["device:type:recipient"],
      ["device:tap:body-field"],
      ["device:type:body", "device:type:greeting"],
      ["device:tap:send-button"],
    ],
  },
  {
    name: "search-and-open",
    steps: [
      ["device:tap:app-icon"],
      ["device:tap:search-field"],
      ["device:type:query"],
      ["device:tap:search-button", "device:shortcut:enter"],
      ["device:scroll:down"],
      ["device:tap:result-item"],
    ],
  },
  {
    name: "settings-toggle",
    steps: [
      ["device:tap:menu-button"],
      ["device:tap:settings-item"],
      ["device:scroll:down", "device:scroll:up"],
      ["device:tap:toggle-control"],
      ["device:tap:back-button"],
    ],
  },
];

/**
 * Produce a deterministic dataset of related movement sequences by sampling
 * step variants from workflow templates. Same seed -> same dataset. The variant
 * sampling yields new-but-related sequences, so a model trained on one split
 * can be measured for generalization on another.
 */
export function generateSyntheticMovementDataset(options: SyntheticMovementOptions): MovementTrainingDataset {
  const workflows = options.workflows ?? DEFAULT_SYNTHETIC_WORKFLOWS;
  const random = makePrng(options.seed);
  const sequences: MovementSequence[] = [];

  for (let index = 0; index < options.sequenceCount; index += 1) {
    const workflow = workflows[Math.floor(random() * workflows.length) % workflows.length];
    if (!workflow) {
      continue;
    }
    const tokens = workflow.steps.map((variants) => {
      const choice = variants[Math.floor(random() * variants.length) % variants.length];
      return choice ?? variants[0] ?? "device:noop";
    });
    sequences.push({ id: `${workflow.name}-${index}`, tokens });
  }

  return { version: 1, sequences };
}

/** Deterministically split a dataset into train/test by stride (no RNG needed). */
export function splitMovementDataset(
  dataset: MovementTrainingDataset,
  holdoutEvery = 4,
): { train: MovementTrainingDataset; test: MovementTrainingDataset } {
  const stride = Math.max(2, Math.trunc(holdoutEvery));
  const train: MovementSequence[] = [];
  const test: MovementSequence[] = [];
  dataset.sequences.forEach((sequence, index) => {
    if (index % stride === stride - 1) {
      test.push(sequence);
    } else {
      train.push(sequence);
    }
  });
  return {
    train: { version: 1, sequences: train },
    test: { version: 1, sequences: test },
  };
}
